name: Lets_Chat
on: push
jobs: 
  lets_chat:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat lets_chart.txt)"
